# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\oriro\Desktop\Zoombo\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcome(object):
    def setupUi(self, welcome):
        welcome.setObjectName("welcome")
        welcome.resize(1646, 942)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(welcome.sizePolicy().hasHeightForWidth())
        welcome.setSizePolicy(sizePolicy)
        welcome.setMinimumSize(QtCore.QSize(1646, 942))
        welcome.setMaximumSize(QtCore.QSize(1646, 942))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 81, 169))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        welcome.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\oriro\\Desktop\\Zoombo\\LOGO/Zoombo Rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        welcome.setWindowIcon(icon)
        welcome.setAutoFillBackground(False)
        welcome.setStyleSheet("background-color: rgb(120, 81, 169);\n"
"\n"
"\n"
"")
        welcome.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase)
        welcome.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(welcome)
        self.centralwidget.setObjectName("centralwidget")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(540, 590, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiLight")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.connectButton.setFont(font)
        self.connectButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;  /* Pure White */\n"
"    color: #5A3D85;  /* Elegant Purple Text */\n"
"    border: 2px solid #C8A2C8;  /* Soft Pastel Purple Border */\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    transition: all 3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F8F1FF;  /* Very Light Purple */\n"
"    border: 2px solid #A175A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D4F0;  /* Subtle Purple Tint */\n"
"    border: 2px solid #7D4F9F;\n"
"}\n"
"")
        self.connectButton.setObjectName("connectButton")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(890, 590, 241, 101))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiLight")
        font.setPointSize(28)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("QPushButton {\n"
"    background-color: #6A5ACD;\n"
"    color: white;\n"
"    border: 2px solid #483D8B;\n"
"    border-radius: 10px;\n"
"    padding: 8px 15px;\n"
"    transition: all 3s ease-in-out;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #836FFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #483D8B;\n"
"}")
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-3, 30, 1651, 299))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.logo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\\Users\\oriro\\Desktop\\Zoombo\\LOGO/logo no bg.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        spacerItem1 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Name = QtWidgets.QLineEdit(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(570, 400, 531, 71))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(24)
        self.Name.setFont(font)
        self.Name.setMaxLength(20)
        self.Name.setObjectName("Name")
        self.warning = QtWidgets.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(575, 490, 521, 20))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.warning.setFont(font)
        self.warning.setStyleSheet("color: rgb(255, 0, 0);")
        self.warning.setScaledContents(False)
        self.warning.setObjectName("warning")
        welcome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(welcome)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1646, 26))
        self.menubar.setObjectName("menubar")
        welcome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(welcome)
        self.statusbar.setObjectName("statusbar")
        welcome.setStatusBar(self.statusbar)

        self.retranslateUi(welcome)
        QtCore.QMetaObject.connectSlotsByName(welcome)

    def retranslateUi(self, welcome):
        _translate = QtCore.QCoreApplication.translate
        welcome.setWindowTitle(_translate("welcome", "Zoombo "))
        self.connectButton.setText(_translate("welcome", "Connect"))
        self.quitButton.setText(_translate("welcome", "Quit"))
        self.Name.setPlaceholderText(_translate("welcome", "Name"))
        self.warning.setText(_translate("welcome", "WARNING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    welcome = QtWidgets.QMainWindow()
    ui = Ui_welcome()
    ui.setupUi(welcome)
    welcome.show()
    sys.exit(app.exec_())
