# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\oriro\Desktop\Zoombo\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#hi

from PyQt5 import QtCore, QtGui, QtWidgets

import pathlib, os
ROOT = pathlib.Path(__file__).resolve().parent           # V2 or gui
IMG  = lambda n: os.fspath(ROOT / ("imgs" if ROOT.name == "gui" else "gui/imgs") / n)


class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(671, 712)
        home.setMinimumSize(QtCore.QSize(671, 712))
        home.setMaximumSize(QtCore.QSize(671, 712))
        home.setStyleSheet("background-color: rgb(120, 81, 169);\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 0, 351, 71))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(IMG('logo no bg.png')))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 100, 461, 51))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiLight")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(190, 330, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiLight")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.connectButton.setFont(font)
        self.connectButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;  /* Pure White */\n"
"    color: #5A3D85;  /* Elegant Purple Text */\n"
"    border: 2px solid #C8A2C8;  /* Soft Pastel Purple Border */\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    transition: all 3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F8F1FF;  /* Very Light Purple */\n"
"    border: 2px solid #A175A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D4F0;  /* Subtle Purple Tint */\n"
"    border: 2px solid #7D4F9F;\n"
"}\n"
"")
        self.connectButton.setObjectName("connectButton")
        self.Name = QtWidgets.QLineEdit(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(130, 200, 411, 71))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(24)
        self.Name.setFont(font)
        self.Name.setMaxLength(20)
        self.Name.setObjectName("Name")
        self.connectButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton_2.setGeometry(QtCore.QRect(120, 540, 401, 81))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiLight")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.connectButton_2.setFont(font)
        self.connectButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;  /* Pure White */\n"
"    color: #5A3D85;  /* Elegant Purple Text */\n"
"    border: 2px solid #C8A2C8;  /* Soft Pastel Purple Border */\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    transition: all 3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F8F1FF;  /* Very Light Purple */\n"
"    border: 2px solid #A175A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D4F0;  /* Subtle Purple Tint */\n"
"    border: 2px solid #7D4F9F;\n"
"}\n"
"")
        self.connectButton_2.setObjectName("connectButton_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(60, 460, 531, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 671, 26))
        self.menubar.setObjectName("menubar")
        home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(home)
        self.statusbar.setObjectName("statusbar")
        home.setStatusBar(self.statusbar)

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "MainWindow"))
        self.label.setText(_translate("home", "Hello {name} !"))
        self.connectButton.setText(_translate("home", "Join Room"))
        self.Name.setPlaceholderText(_translate("home", "Room Code"))
        self.connectButton_2.setText(_translate("home", "Create New Room"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home = QtWidgets.QMainWindow()
    ui = Ui_home()
    ui.setupUi(home)
    home.show()
    sys.exit(app.exec_())
