# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\oriro\Desktop\Zoombo\room.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1654, 1053)
        MainWindow.setStyleSheet("background-color: rgb(120, 81, 169);\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1591, 122))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.logo.setMaximumSize(QtCore.QSize(540, 120))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\\Users\\oriro\\Desktop\\Zoombo\\LOGO/logo no bg.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cameraButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraButton.sizePolicy().hasHeightForWidth())
        self.cameraButton.setSizePolicy(sizePolicy)
        self.cameraButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\oriro\\Desktop\\Zoombo\\LOGO/camera_green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cameraButton.setIcon(icon)
        self.cameraButton.setIconSize(QtCore.QSize(80, 80))
        self.cameraButton.setCheckable(True)
        self.cameraButton.setChecked(False)
        self.cameraButton.setFlat(True)
        self.cameraButton.setObjectName("cameraButton")
        self.horizontalLayout.addWidget(self.cameraButton)
        self.micButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micButton.sizePolicy().hasHeightForWidth())
        self.micButton.setSizePolicy(sizePolicy)
        self.micButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\oriro\\Desktop\\Zoombo\\LOGO/mic_green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.micButton.setIcon(icon1)
        self.micButton.setIconSize(QtCore.QSize(80, 80))
        self.micButton.setCheckable(True)
        self.micButton.setChecked(False)
        self.micButton.setFlat(True)
        self.micButton.setObjectName("micButton")
        self.horizontalLayout.addWidget(self.micButton)
        self.SettingsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiLight")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.SettingsButton.setFont(font)
        self.SettingsButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;  /* Pure White */\n"
"    color: #5A3D85;  /* Elegant Purple Text */\n"
"    border: 2px solid #C8A2C8;  /* Soft Pastel Purple Border */\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    transition: all 3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F8F1FF;  /* Very Light Purple */\n"
"    border: 2px solid #A175A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D4F0;  /* Subtle Purple Tint */\n"
"    border: 2px solid #7D4F9F;\n"
"}\n"
"")
        self.SettingsButton.setObjectName("SettingsButton")
        self.horizontalLayout.addWidget(self.SettingsButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 140, 1571, 851))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        self.graphicsView_8.setSizeIncrement(QtCore.QSize(8, 5))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.gridLayout_2.addWidget(self.graphicsView_8, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        self.graphicsView_7.setSizeIncrement(QtCore.QSize(8, 5))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.gridLayout_2.addWidget(self.graphicsView_7, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        self.graphicsView_9.setSizeIncrement(QtCore.QSize(8, 5))
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.gridLayout_2.addWidget(self.graphicsView_9, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 3, 1, 1)
        self.graphicsView_12 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        self.graphicsView_12.setSizeIncrement(QtCore.QSize(8, 5))
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.gridLayout_2.addWidget(self.graphicsView_12, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_2)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem8)
        self.messageBox = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.messageBox.setObjectName("messageBox")
        self.verticalLayout.addWidget(self.messageBox)
        self.sendButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiLight")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.sendButton.setFont(font)
        self.sendButton.setStyleSheet("QPushButton {\n"
"    background-color: #E6E6FA;  /* Very Light Purple */\n"
"    color: #5A3D85;  /* Elegant Purple Text */\n"
"    border: 2px solid #C8A2C8;  /* Soft Pastel Purple Border */\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"    transition: all 3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F8F1FF;  /* Very Light Purple */\n"
"    border: 2px solid #A175A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E6D4F0;  /* Subtle Purple Tint */\n"
"    border: 2px solid #7D4F9F;\n"
"}\n"
"")
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout.addWidget(self.sendButton)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1654, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ROOM ID: 7DNHG5"))
        self.SettingsButton.setText(_translate("MainWindow", "Settings"))
        self.sendButton.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
